Refactoring contracts to make library package
icon-project/btp2-solidity pull request #5
Opened 2023-05-18 06:07 UTC by mksong-icon

Add new package "@iconfoundation/btp2-solidity-library"
Remove redundant RLPDecode/Encode.sol from other contracts
Consolidate related contract codes
Fix problem and optimize some methods in RLPEncode.sol
Support decoding large number in RLPDecode.sol

2023-05-19 07:33 UTC, jspark-icon approved these changes

2023-05-19 08:05 UTC, kornery approved these changes

2023-05-19 08:23 UTC, sink772 commented on library/package.json
> +  "files": [ "contracts/*.sol" ]
Wouldn't it be right to modify it like this?
```suggestion
  "files": [ "contracts/utils/*.sol" ]
```

2023-05-19 09:38 UTC, sink772 requested changes

2023-05-19 09:38 UTC, sink772 commented on xcall/package.json
> +    "@iconfoundation/btp-solidity-library": "file:../library",
```suggestion
    "@iconfoundation/btp2-solidity-library": "file:../library",
```

2023-05-19 09:38 UTC, sink772 commented on xcall/yarn.lock
> +"@iconfoundation/btp-solidity-library@file:../library":
```suggestion
"@iconfoundation/btp2-solidity-library@file:../library":
```

2023-05-23 02:38 UTC, sink772 approved these changes

2023-05-23 02:40 UTC, merged